version: '3.8'

services:
  java-login-app:
    build:
      context: .
    container_name: java-login-app-container
    ports:
      - "8082:8080"  # hostPort:containerPort (Tomcat always runs on 8080 inside)
